### ISSUE TITLE
Unable to Start Mongo Container: Entry Point Exec Format Error

### ISSUE THREAD

**Issue by Saumyajeet-Varma** [Saumyajeet-Varma/Docker-TestApp#1]
# ❗️ Issue #1: MongoDB Container Fails to Start — `exec format error`

## Description
When running the Dockerized application using `docker-compose up`, the MongoDB service fails to start with the following error:

```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

This indicates an architecture mismatch between the MongoDB Docker image and the host machine.

## Request for Suggestions

If you notice any misconfigurations or have suggestions to improve the docker-compose.yml setup (especially for better compatibility or best practices), I’d appreciate your input.

```yaml
version: '3'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
```

Feel free to suggest alternative ways to handle platform issues

## Contribution

If you'd like to contribute a fix or improvements to the YAML configuration or documentation, feel free to open a pull request. All contributions are appreciated!
